PIDs:
  NUX:
    kp: 28.50
    kd: 15.50
    ki: 15.0
    minOutput: -800.0
    maxOutput: 800.0
    integratorMin: -0.1
    integratorMax: 0.1
  NUY:
    kp: 28.50
    kd: 15.50
    ki: 15.0
    minOutput: -800.0
    maxOutput: 800.0
    integratorMin: -0.1
    integratorMax: 0.1
  NUZ:
    kp: 75.0
    kd: 30.0
    ki: 38.00
    minOutput: -300.0
    maxOutput: 300.0
    integratorMin: -10
    integratorMax: 10

  Yaw:
    kp: -200.0
    kd: -20.0
    ki: 0.0
    minOutput: -200.0
    maxOutput: 200.0
    integratorMin: 0.0
    integratorMax: 0.0
