PIDs:
  NUX:
    kp: 22.5
    kd: 16.5
    ki: 5.0
    minOutput: -800.0
    maxOutput: 800.0
    integratorMin: -1
    integratorMax: 1
  NUY:
    kp: 22.5
    kd: 12.5
    ki: 5.0
    minOutput: -800.0
    maxOutput: 800.0
    integratorMin: -1
    integratorMax: 1
  NUZ:
    kp: 175.7
    kd: 45.0
    ki: 35.0
    minOutput: 0.0
    maxOutput: 300.0
    integratorMin: -100
    integratorMax: 100
  Yaw:
    kp: -200.0
    kd: -20.0
    ki: 0.0
    minOutput: -200.0
    maxOutput: 200.0
    integratorMin: 0.0
    integratorMax: 0.0
